### ISSUE TITLE
Limit vertical size of table "Experiments for user ..."

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/UserAccess#4]
A user with hundreds of experiments will have all of them displayed every time the "StatusExperiment" page is opened. 
Experiment status is displayed below.
As a first step, the table size should be limited, so that you can actually see the experiment summary and status on the same page. 
Eventually, we will need the pagination presented in the mockup.

**Comment by mikepeon** [comment]
The experiment details are now inlined, so this should save the scrolling down/up hassle. Also, allows to see more than one experiment details at the same time.
Client-side pagination will be implemented afterwards, if needed.
