### ISSUE TITLE
Implement support for displaying user/node quota journal

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/UserAccess#7]
e.g.
https://scheduler.monroe-system.eu/v1/users/127/journals
https://scheduler.monroe-system.eu/v1/resources/27/journals 
(the latter route seems to duplicate some other data atm, that should be fixed soon)

**Comment by mikepeon** [comment]
The user journal can be presented in the "My account" tab.
Should the resource journal be presented for regular users?

**Comment by ozgualay** [comment]
I think everyone should see their own journal.

Özgü

**Comment by mikepeon** [comment]
User journal is fully implemented in the "My account" tab.
Node journal is not yet implemented.
